
FROM node:20.11.1 AS build-stage

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

FROM node:20.11.1 AS production-stage

WORKDIR /app

RUN npm install express

COPY --from=build-stage /app/build ./build

COPY server.js .

EXPOSE 3000

CMD ["node", "server.js"]
