apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskzen-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskzen-backend
  template:
    metadata:
      labels:
        app: taskzen-backend
    spec:
      containers:
      - name: taskzen-backend
        image: ghcr.io/aswanyaugustine123/taskzen-backend:latest
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URI
            value: "mongodb+srv://aswanyaugustine1992:AnnieGeorge1962@democluster.mqu7a.mongodb.net/taskzen?retryWrites=true&w=majority&appName=demoCluster"
      imagePullSecrets:
        - name: ghcr-creds

---
apiVersion: v1
kind: Service
metadata:
  name: taskzen-backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: taskzen-backend
