apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskzen-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskzen-backend
  template:
    metadata:
      labels:
        app: taskzen-backend
    spec:
      containers:
      - name: taskzen-backend
        image: ghcr.io/aswanyaugustine123/taskzen-backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: taskzen-backend-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: taskzen-backend
