name: CI/CD Pipeline

on:
  workflow_dispatch

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PATTOKEN }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ghcr.io/aswanyaugustine123/taskzen-frontend:latest

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ghcr.io/aswanyaugustine123/taskzen-backend:latest

  deploy-to-eks:
    name: Deploy to EKS
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy Backend
        run: kubectl apply -f ./k8s/backend-deployment-service.yaml

      - name: Check Backend Deployment Status
        run: kubectl rollout status deployment/taskzen-backend-deployment

      - name: Get LoadBalancer public IP
        id: get-lb-ip
        run: |
          LB_IP=$(kubectl get svc taskzen-backend-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "::set-output name=lb_ip::$LB_IP"

      - name: Deploy Frontend
        run: |
          sed -i "s|REACT_APP_BACKEND_URL=.*|REACT_APP_BACKEND_URL=http://$LB_IP:3000|g" ./k8s/frontend-deployment-service.yaml
          kubectl apply -f ./k8s/frontend-deployment-service.yaml

      - name: Check Frontend Deployment Status
        run: kubectl rollout status deployment/taskzen-frontend-deployment
